substitutions:
  name: "one"
  heater: input_boolean.tut_thermo_fire ### Remove for single Control Thermostat
  cooler: switch.fan_window_master
  fan_speed: number.fan_window_speed
  temperature_sensor: input_number.fake_one_temp

esphome:
  name: 1-themostat
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:

sensor:
  - platform: homeassistant
    id: room_temperature
    entity_id: $temperature_sensor
    internal: true

climate:
  - platform: thermostat
    name: $name Thermostat
    id: this_thermostat
    visual:
      min_temperature: 15
      max_temperature: 40
    sensor: room_temperature

    default_target_temperature_low: 18.0  ### Remove for single Control Thermostat
    default_target_temperature_high: 22.0
    min_cooling_off_time: 1s
    min_cooling_run_time: 1s
    min_heating_off_time: 1s              ### Remove for single Control Thermostat
    min_heating_run_time: 1s              ### Remove for single Control Thermostat
    min_idle_time: 1s
    cool_action:
      - homeassistant.service:
          service: homeassistant.turn_on
          data:
            entity_id: $cooler

### Remove for single Control Thermostat ####
    heat_action:
      - homeassistant.service:
          service: homeassistant.turn_on
          data:
            entity_id: $heater
#############################################

    idle_action:
      - homeassistant.service:
          service: homeassistant.turn_off
          data:
            entity_id: $cooler

### Remove for single Control Thermostat ####
      - homeassistant.service:
          service: homeassistant.turn_off
          data:
            entity_id: $heater
#############################################

    on_state:
      - if:
          condition:
            - lambda: "return (id(this_thermostat).mode) != 0;"
          then:
            - homeassistant.service:
                service: number.set_value
                data:
                  entity_id: $fan_speed
                  value: !lambda |-
                    if (id(this_thermostat).current_temperature > id(this_thermostat).target_temperature_high +6) {
                     return "3";
                     }
                    if (id(this_thermostat).current_temperature > id(this_thermostat).target_temperature_high +3) {
                     return "2";
                    } else {
                     return "1";
                    }
